/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TZStandaloneSetup extends TZStandaloneSetupGenerated {

	def static void doSetup() {
		new TZStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
