# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rijo/Downloads/Timer/hHM/hHM.cache/wt [current_project]
set_property parent.project_path /home/rijo/Downloads/Timer/hHM/hHM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo /home/rijo/Downloads/Timer/hHM/hHM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/rijo/Downloads/Timer/hHM/hHM.srcs/sources_1/new/timer32b.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top timer32b -part xc7z010clg400-1


write_checkpoint -force -noxdef timer32b.dcp

catch { report_utilization -file timer32b_utilization_synth.rpt -pb timer32b_utilization_synth.pb }
