/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz;

import org.xtext.example.tz.AbstractTZRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TZRuntimeModule extends AbstractTZRuntimeModule {
}
