/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz;

import org.xtext.example.tz.TZStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TZStandaloneSetup extends TZStandaloneSetupGenerated {
  public static void doSetup() {
    TZStandaloneSetup _tZStandaloneSetup = new TZStandaloneSetup();
    _tZStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
