/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.tz.parser.antlr.internal.InternalTZParser;
import org.xtext.example.tz.services.TZGrammarAccess;

public class TZParser extends AbstractAntlrParser {

	@Inject
	private TZGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTZParser createParser(XtextTokenStream stream) {
		return new InternalTZParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TZGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TZGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
