/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.tZ.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.tz.tZ.CONSTANT;
import org.xtext.example.tz.tZ.MODULE;
import org.xtext.example.tz.tZ.Model;
import org.xtext.example.tz.tZ.TZPackage;
import org.xtext.example.tz.tZ.TZVISOR;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tz.tZ.impl.ModelImpl#getModule <em>Module</em>}</li>
 *   <li>{@link org.xtext.example.tz.tZ.impl.ModelImpl#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.example.tz.tZ.impl.ModelImpl#getTzvisor <em>Tzvisor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getModule() <em>Module</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModule()
   * @generated
   * @ordered
   */
  protected EList<MODULE> module;

  /**
   * The cached value of the '{@link #getConstant() <em>Constant</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstant()
   * @generated
   * @ordered
   */
  protected EList<CONSTANT> constant;

  /**
   * The cached value of the '{@link #getTzvisor() <em>Tzvisor</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTzvisor()
   * @generated
   * @ordered
   */
  protected EList<TZVISOR> tzvisor;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TZPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<MODULE> getModule()
  {
    if (module == null)
    {
      module = new EObjectContainmentEList<MODULE>(MODULE.class, this, TZPackage.MODEL__MODULE);
    }
    return module;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<CONSTANT> getConstant()
  {
    if (constant == null)
    {
      constant = new EObjectContainmentEList<CONSTANT>(CONSTANT.class, this, TZPackage.MODEL__CONSTANT);
    }
    return constant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<TZVISOR> getTzvisor()
  {
    if (tzvisor == null)
    {
      tzvisor = new EObjectContainmentEList<TZVISOR>(TZVISOR.class, this, TZPackage.MODEL__TZVISOR);
    }
    return tzvisor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TZPackage.MODEL__MODULE:
        return ((InternalEList<?>)getModule()).basicRemove(otherEnd, msgs);
      case TZPackage.MODEL__CONSTANT:
        return ((InternalEList<?>)getConstant()).basicRemove(otherEnd, msgs);
      case TZPackage.MODEL__TZVISOR:
        return ((InternalEList<?>)getTzvisor()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TZPackage.MODEL__MODULE:
        return getModule();
      case TZPackage.MODEL__CONSTANT:
        return getConstant();
      case TZPackage.MODEL__TZVISOR:
        return getTzvisor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TZPackage.MODEL__MODULE:
        getModule().clear();
        getModule().addAll((Collection<? extends MODULE>)newValue);
        return;
      case TZPackage.MODEL__CONSTANT:
        getConstant().clear();
        getConstant().addAll((Collection<? extends CONSTANT>)newValue);
        return;
      case TZPackage.MODEL__TZVISOR:
        getTzvisor().clear();
        getTzvisor().addAll((Collection<? extends TZVISOR>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TZPackage.MODEL__MODULE:
        getModule().clear();
        return;
      case TZPackage.MODEL__CONSTANT:
        getConstant().clear();
        return;
      case TZPackage.MODEL__TZVISOR:
        getTzvisor().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TZPackage.MODEL__MODULE:
        return module != null && !module.isEmpty();
      case TZPackage.MODEL__CONSTANT:
        return constant != null && !constant.isEmpty();
      case TZPackage.MODEL__TZVISOR:
        return tzvisor != null && !tzvisor.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
