/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.tZ.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.tz.tZ.CONSTANT;
import org.xtext.example.tz.tZ.MODULE;
import org.xtext.example.tz.tZ.TZPackage;
import org.xtext.example.tz.tZ.TZVISOR;
import org.xtext.example.tz.tZ.VARIABLES;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>VISOR</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tz.tZ.impl.TZVISORImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.tz.tZ.impl.TZVISORImpl#getVariables <em>Variables</em>}</li>
 *   <li>{@link org.xtext.example.tz.tZ.impl.TZVISORImpl#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.example.tz.tZ.impl.TZVISORImpl#getModule <em>Module</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TZVISORImpl extends MinimalEObjectImpl.Container implements TZVISOR
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getVariables() <em>Variables</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariables()
   * @generated
   * @ordered
   */
  protected EList<VARIABLES> variables;

  /**
   * The cached value of the '{@link #getConstant() <em>Constant</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstant()
   * @generated
   * @ordered
   */
  protected EList<CONSTANT> constant;

  /**
   * The cached value of the '{@link #getModule() <em>Module</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModule()
   * @generated
   * @ordered
   */
  protected EList<MODULE> module;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TZVISORImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TZPackage.Literals.TZ_VISOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TZPackage.TZ_VISOR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<VARIABLES> getVariables()
  {
    if (variables == null)
    {
      variables = new EObjectContainmentEList<VARIABLES>(VARIABLES.class, this, TZPackage.TZ_VISOR__VARIABLES);
    }
    return variables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<CONSTANT> getConstant()
  {
    if (constant == null)
    {
      constant = new EObjectContainmentEList<CONSTANT>(CONSTANT.class, this, TZPackage.TZ_VISOR__CONSTANT);
    }
    return constant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<MODULE> getModule()
  {
    if (module == null)
    {
      module = new EObjectContainmentEList<MODULE>(MODULE.class, this, TZPackage.TZ_VISOR__MODULE);
    }
    return module;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TZPackage.TZ_VISOR__VARIABLES:
        return ((InternalEList<?>)getVariables()).basicRemove(otherEnd, msgs);
      case TZPackage.TZ_VISOR__CONSTANT:
        return ((InternalEList<?>)getConstant()).basicRemove(otherEnd, msgs);
      case TZPackage.TZ_VISOR__MODULE:
        return ((InternalEList<?>)getModule()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TZPackage.TZ_VISOR__NAME:
        return getName();
      case TZPackage.TZ_VISOR__VARIABLES:
        return getVariables();
      case TZPackage.TZ_VISOR__CONSTANT:
        return getConstant();
      case TZPackage.TZ_VISOR__MODULE:
        return getModule();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TZPackage.TZ_VISOR__NAME:
        setName((String)newValue);
        return;
      case TZPackage.TZ_VISOR__VARIABLES:
        getVariables().clear();
        getVariables().addAll((Collection<? extends VARIABLES>)newValue);
        return;
      case TZPackage.TZ_VISOR__CONSTANT:
        getConstant().clear();
        getConstant().addAll((Collection<? extends CONSTANT>)newValue);
        return;
      case TZPackage.TZ_VISOR__MODULE:
        getModule().clear();
        getModule().addAll((Collection<? extends MODULE>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TZPackage.TZ_VISOR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TZPackage.TZ_VISOR__VARIABLES:
        getVariables().clear();
        return;
      case TZPackage.TZ_VISOR__CONSTANT:
        getConstant().clear();
        return;
      case TZPackage.TZ_VISOR__MODULE:
        getModule().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TZPackage.TZ_VISOR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TZPackage.TZ_VISOR__VARIABLES:
        return variables != null && !variables.isEmpty();
      case TZPackage.TZ_VISOR__CONSTANT:
        return constant != null && !constant.isEmpty();
      case TZPackage.TZ_VISOR__MODULE:
        return module != null && !module.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //TZVISORImpl
