/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.validation;

import org.xtext.example.tz.validation.AbstractTZValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TZValidator extends AbstractTZValidator {
}
