/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.tZ;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tz.tZ.Model#getModule <em>Module</em>}</li>
 *   <li>{@link org.xtext.example.tz.tZ.Model#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.example.tz.tZ.Model#getTzvisor <em>Tzvisor</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tz.tZ.TZPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Module</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tz.tZ.MODULE}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Module</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module</em>' containment reference list.
   * @see org.xtext.example.tz.tZ.TZPackage#getModel_Module()
   * @model containment="true"
   * @generated
   */
  EList<MODULE> getModule();

  /**
   * Returns the value of the '<em><b>Constant</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tz.tZ.CONSTANT}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' containment reference list.
   * @see org.xtext.example.tz.tZ.TZPackage#getModel_Constant()
   * @model containment="true"
   * @generated
   */
  EList<CONSTANT> getConstant();

  /**
   * Returns the value of the '<em><b>Tzvisor</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.tz.tZ.TZVISOR}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tzvisor</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tzvisor</em>' containment reference list.
   * @see org.xtext.example.tz.tZ.TZPackage#getModel_Tzvisor()
   * @model containment="true"
   * @generated
   */
  EList<TZVISOR> getTzvisor();

} // Model
