/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.tZ;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.tz.tZ.TZPackage
 * @generated
 */
public interface TZFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TZFactory eINSTANCE = org.xtext.example.tz.tZ.impl.TZFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>VISOR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VISOR</em>'.
   * @generated
   */
  TZVISOR createTZVISOR();

  /**
   * Returns a new object of class '<em>MODULE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MODULE</em>'.
   * @generated
   */
  MODULE createMODULE();

  /**
   * Returns a new object of class '<em>LABEL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LABEL</em>'.
   * @generated
   */
  LABEL createLABEL();

  /**
   * Returns a new object of class '<em>CONSTANT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CONSTANT</em>'.
   * @generated
   */
  CONSTANT createCONSTANT();

  /**
   * Returns a new object of class '<em>VARIABLES</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VARIABLES</em>'.
   * @generated
   */
  VARIABLES createVARIABLES();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TZPackage getTZPackage();

} //TZFactory
