/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.tZ;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.tz.tZ.TZFactory
 * @model kind="package"
 * @generated
 */
public interface TZPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tZ";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/tz/TZ";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tZ";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TZPackage eINSTANCE = org.xtext.example.tz.tZ.impl.TZPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.tz.tZ.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tz.tZ.impl.ModelImpl
   * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Module</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODULE = 0;

  /**
   * The feature id for the '<em><b>Constant</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONSTANT = 1;

  /**
   * The feature id for the '<em><b>Tzvisor</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TZVISOR = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.tz.tZ.impl.TZVISORImpl <em>VISOR</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tz.tZ.impl.TZVISORImpl
   * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getTZVISOR()
   * @generated
   */
  int TZ_VISOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TZ_VISOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TZ_VISOR__VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Constant</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TZ_VISOR__CONSTANT = 2;

  /**
   * The feature id for the '<em><b>Module</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TZ_VISOR__MODULE = 3;

  /**
   * The number of structural features of the '<em>VISOR</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TZ_VISOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.tz.tZ.impl.MODULEImpl <em>MODULE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tz.tZ.impl.MODULEImpl
   * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getMODULE()
   * @generated
   */
  int MODULE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Label</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__LABEL = 1;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__SUPER_TYPE = 2;

  /**
   * The number of structural features of the '<em>MODULE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.tz.tZ.impl.LABELImpl <em>LABEL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tz.tZ.impl.LABELImpl
   * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getLABEL()
   * @generated
   */
  int LABEL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__SUPER_TYPE = 1;

  /**
   * The number of structural features of the '<em>LABEL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.tz.tZ.impl.CONSTANTImpl <em>CONSTANT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tz.tZ.impl.CONSTANTImpl
   * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getCONSTANT()
   * @generated
   */
  int CONSTANT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__NAME = 0;

  /**
   * The number of structural features of the '<em>CONSTANT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.tz.tZ.impl.VARIABLESImpl <em>VARIABLES</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.tz.tZ.impl.VARIABLESImpl
   * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getVARIABLES()
   * @generated
   */
  int VARIABLES = 5;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES__SUPER_TYPE = 0;

  /**
   * The number of structural features of the '<em>VARIABLES</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.tz.tZ.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.tz.tZ.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tz.tZ.Model#getModule <em>Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Module</em>'.
   * @see org.xtext.example.tz.tZ.Model#getModule()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Module();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tz.tZ.Model#getConstant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constant</em>'.
   * @see org.xtext.example.tz.tZ.Model#getConstant()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Constant();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tz.tZ.Model#getTzvisor <em>Tzvisor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tzvisor</em>'.
   * @see org.xtext.example.tz.tZ.Model#getTzvisor()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tzvisor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tz.tZ.TZVISOR <em>VISOR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>VISOR</em>'.
   * @see org.xtext.example.tz.tZ.TZVISOR
   * @generated
   */
  EClass getTZVISOR();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tz.tZ.TZVISOR#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.tz.tZ.TZVISOR#getName()
   * @see #getTZVISOR()
   * @generated
   */
  EAttribute getTZVISOR_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tz.tZ.TZVISOR#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see org.xtext.example.tz.tZ.TZVISOR#getVariables()
   * @see #getTZVISOR()
   * @generated
   */
  EReference getTZVISOR_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tz.tZ.TZVISOR#getConstant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constant</em>'.
   * @see org.xtext.example.tz.tZ.TZVISOR#getConstant()
   * @see #getTZVISOR()
   * @generated
   */
  EReference getTZVISOR_Constant();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tz.tZ.TZVISOR#getModule <em>Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Module</em>'.
   * @see org.xtext.example.tz.tZ.TZVISOR#getModule()
   * @see #getTZVISOR()
   * @generated
   */
  EReference getTZVISOR_Module();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tz.tZ.MODULE <em>MODULE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MODULE</em>'.
   * @see org.xtext.example.tz.tZ.MODULE
   * @generated
   */
  EClass getMODULE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tz.tZ.MODULE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.tz.tZ.MODULE#getName()
   * @see #getMODULE()
   * @generated
   */
  EAttribute getMODULE_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.tz.tZ.MODULE#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Label</em>'.
   * @see org.xtext.example.tz.tZ.MODULE#getLabel()
   * @see #getMODULE()
   * @generated
   */
  EReference getMODULE_Label();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.tz.tZ.MODULE#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.xtext.example.tz.tZ.MODULE#getSuperType()
   * @see #getMODULE()
   * @generated
   */
  EReference getMODULE_SuperType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tz.tZ.LABEL <em>LABEL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LABEL</em>'.
   * @see org.xtext.example.tz.tZ.LABEL
   * @generated
   */
  EClass getLABEL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tz.tZ.LABEL#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.tz.tZ.LABEL#getName()
   * @see #getLABEL()
   * @generated
   */
  EAttribute getLABEL_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.tz.tZ.LABEL#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.xtext.example.tz.tZ.LABEL#getSuperType()
   * @see #getLABEL()
   * @generated
   */
  EReference getLABEL_SuperType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tz.tZ.CONSTANT <em>CONSTANT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CONSTANT</em>'.
   * @see org.xtext.example.tz.tZ.CONSTANT
   * @generated
   */
  EClass getCONSTANT();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.tz.tZ.CONSTANT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.tz.tZ.CONSTANT#getName()
   * @see #getCONSTANT()
   * @generated
   */
  EAttribute getCONSTANT_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.tz.tZ.VARIABLES <em>VARIABLES</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>VARIABLES</em>'.
   * @see org.xtext.example.tz.tZ.VARIABLES
   * @generated
   */
  EClass getVARIABLES();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.tz.tZ.VARIABLES#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.xtext.example.tz.tZ.VARIABLES#getSuperType()
   * @see #getVARIABLES()
   * @generated
   */
  EReference getVARIABLES_SuperType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TZFactory getTZFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.tz.tZ.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tz.tZ.impl.ModelImpl
     * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Module</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODULE = eINSTANCE.getModel_Module();

    /**
     * The meta object literal for the '<em><b>Constant</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONSTANT = eINSTANCE.getModel_Constant();

    /**
     * The meta object literal for the '<em><b>Tzvisor</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TZVISOR = eINSTANCE.getModel_Tzvisor();

    /**
     * The meta object literal for the '{@link org.xtext.example.tz.tZ.impl.TZVISORImpl <em>VISOR</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tz.tZ.impl.TZVISORImpl
     * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getTZVISOR()
     * @generated
     */
    EClass TZ_VISOR = eINSTANCE.getTZVISOR();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TZ_VISOR__NAME = eINSTANCE.getTZVISOR_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TZ_VISOR__VARIABLES = eINSTANCE.getTZVISOR_Variables();

    /**
     * The meta object literal for the '<em><b>Constant</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TZ_VISOR__CONSTANT = eINSTANCE.getTZVISOR_Constant();

    /**
     * The meta object literal for the '<em><b>Module</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TZ_VISOR__MODULE = eINSTANCE.getTZVISOR_Module();

    /**
     * The meta object literal for the '{@link org.xtext.example.tz.tZ.impl.MODULEImpl <em>MODULE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tz.tZ.impl.MODULEImpl
     * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getMODULE()
     * @generated
     */
    EClass MODULE = eINSTANCE.getMODULE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODULE__NAME = eINSTANCE.getMODULE_Name();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULE__LABEL = eINSTANCE.getMODULE_Label();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULE__SUPER_TYPE = eINSTANCE.getMODULE_SuperType();

    /**
     * The meta object literal for the '{@link org.xtext.example.tz.tZ.impl.LABELImpl <em>LABEL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tz.tZ.impl.LABELImpl
     * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getLABEL()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLABEL();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__NAME = eINSTANCE.getLABEL_Name();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL__SUPER_TYPE = eINSTANCE.getLABEL_SuperType();

    /**
     * The meta object literal for the '{@link org.xtext.example.tz.tZ.impl.CONSTANTImpl <em>CONSTANT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tz.tZ.impl.CONSTANTImpl
     * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getCONSTANT()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getCONSTANT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__NAME = eINSTANCE.getCONSTANT_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.tz.tZ.impl.VARIABLESImpl <em>VARIABLES</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.tz.tZ.impl.VARIABLESImpl
     * @see org.xtext.example.tz.tZ.impl.TZPackageImpl#getVARIABLES()
     * @generated
     */
    EClass VARIABLES = eINSTANCE.getVARIABLES();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLES__SUPER_TYPE = eINSTANCE.getVARIABLES_SuperType();

  }

} //TZPackage
