/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.tZ;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VARIABLES</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.tz.tZ.VARIABLES#getSuperType <em>Super Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.tz.tZ.TZPackage#getVARIABLES()
 * @model
 * @generated
 */
public interface VARIABLES extends EObject
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Super Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(EObject)
   * @see org.xtext.example.tz.tZ.TZPackage#getVARIABLES_SuperType()
   * @model
   * @generated
   */
  EObject getSuperType();

  /**
   * Sets the value of the '{@link org.xtext.example.tz.tZ.VARIABLES#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(EObject value);

} // VARIABLES
