/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.tz.ui.internal.TzActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TZExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TzActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TzActivator.getInstance().getInjector(TzActivator.ORG_XTEXT_EXAMPLE_TZ_TZ);
	}
	
}
