/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTZScopeProvider extends DelegatingScopeProvider {
}
