/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.tz.services.TZGrammarAccess;

@SuppressWarnings("all")
public class TZSyntacticSequencer extends AbstractSyntacticSequencer {

	protected TZGrammarAccess grammarAccess;
	protected AbstractElementAlias match_MODULE_CFIKeyword_0_3_or_DFIKeyword_0_2_or_HMKeyword_0_4_or_IPCKeyword_0_1_or_SBOOTKeyword_0_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (TZGrammarAccess) access;
		match_MODULE_CFIKeyword_0_3_or_DFIKeyword_0_2_or_HMKeyword_0_4_or_IPCKeyword_0_1_or_SBOOTKeyword_0_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getMODULEAccess().getCFIKeyword_0_3()), new TokenAlias(false, false, grammarAccess.getMODULEAccess().getDFIKeyword_0_2()), new TokenAlias(false, false, grammarAccess.getMODULEAccess().getHMKeyword_0_4()), new TokenAlias(false, false, grammarAccess.getMODULEAccess().getIPCKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getMODULEAccess().getSBOOTKeyword_0_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getINTRule())
			return getINTToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal INT returns ecore::EInt: ('0'..'9')+;
	 */
	protected String getINTToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_MODULE_CFIKeyword_0_3_or_DFIKeyword_0_2_or_HMKeyword_0_4_or_IPCKeyword_0_1_or_SBOOTKeyword_0_0.equals(syntax))
				emit_MODULE_CFIKeyword_0_3_or_DFIKeyword_0_2_or_HMKeyword_0_4_or_IPCKeyword_0_1_or_SBOOTKeyword_0_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'SBOOT' | 'IPC' | 'DFI' | 'CFI' | 'HM'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 */
	protected void emit_MODULE_CFIKeyword_0_3_or_DFIKeyword_0_2_or_HMKeyword_0_4_or_IPCKeyword_0_1_or_SBOOTKeyword_0_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
