/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.tz.ui.internal.TzActivator;

public class TZUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TzActivator.getInstance().getInjector("org.xtext.example.tz.TZ");
	}

}
