/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.tz.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.tz.ui.AbstractTZUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TZUiModule extends AbstractTZUiModule {
  public TZUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
